version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: propertyuser
      POSTGRES_PASSWORD: propertypass
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
