version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: propertydb
      POSTGRES_USER: propertyuser
      POSTGRES_PASSWORD: propertypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persistent data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # persistent data

# Define named volumes
volumes:
  postgres_data:
  redis_data:
